// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfNfXXwqFUzLDQSoQDygsdI4qVU3dGENE',
    appId: '1:875954583146:web:99a27094e19ecea9b23c13',
    messagingSenderId: '875954583146',
    projectId: 'test-2055',
    authDomain: 'test-2055.firebaseapp.com',
    storageBucket: 'test-2055.appspot.com',
    measurementId: 'G-MB7HW44G6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDsEwyfwSBVx7eWCdWjLcNXHybsOXPhQ4',
    appId: '1:875954583146:android:a18d6b481c313443b23c13',
    messagingSenderId: '875954583146',
    projectId: 'test-2055',
    storageBucket: 'test-2055.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_z_dzUaBYOOxDBo7MO7Sq2vC4nGHMpJU',
    appId: '1:875954583146:ios:315807e0a4154be2b23c13',
    messagingSenderId: '875954583146',
    projectId: 'test-2055',
    storageBucket: 'test-2055.appspot.com',
    iosClientId: '875954583146-mhug9fdmnodh1o774m5uc60e9n1iren5.apps.googleusercontent.com',
    iosBundleId: 'com.t4ulabs.baniBayram',
  );
}
